name = "is_container"
version = "1.0.0"
description = "Check whether you're running inside a container"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowlabs-hq", repo = "is_container" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.7.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
